# Generated by Django 5.2.10 on 2026-01-31 19:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_favorite_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'source_language', 'target_language', 'original_text', 'translated_text')},
        ),
    ]
